import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'or' | 'as' | 'raj';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    appName: 'EduIndia',
    tagline: 'Learning for Rural India',
    home: 'Home',
    lectures: 'Lectures',
    assignments: 'Assignments',
    discussions: 'Discussions',
    profile: 'Profile',
    joinLiveClass: 'Join Live Class',
    uploadLecture: 'Upload Lecture',
    lectureTitle: 'Lecture Title',
    subject: 'Subject',
    description: 'Description',
    optimizeForLowBandwidth: 'Optimize for Low Bandwidth',
    recordedLectures: 'Recorded Lectures',
    aiAssistant: 'AI Assistant',
    typeYourDoubt: 'Type your doubt...',
    explainTopic: 'Explain Topic',
    summarizeLecture: 'Summarize Lecture',
    answerQuiz: 'Answer Quiz',
    howToUse: 'How to Use',
    callSupport: 'Call Support',
    tollFreeNumber: 'Toll-Free: 1800-XXX-XXXX',
    offlineMode: 'Offline Mode',
    downloadForOffline: 'Download for Offline',
    culturalGreeting: 'Namaste! Welcome to learning',
    welcomeMessage: 'Welcome to EduIndia',
    todaysLectures: "Today's Lectures",
    myProgress: 'My Progress',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    upcomingClasses: 'Upcoming Classes',
    featuredCourses: 'Featured Courses',
    studyMaterials: 'Study Materials',
    practiceTests: 'Practice Tests',
    achievements: 'Achievements',
    notifications: 'Notifications',
  },
  hi: {
    appName: 'एडुइंडिया',
    tagline: 'ग्रामीण भारत के लिए शिक्षा',
    home: 'होम',
    lectures: 'व्याख्यान',
    assignments: 'असाइनमेंट',
    discussions: 'चर्चा',
    profile: 'प्रोफाइल',
    joinLiveClass: 'लाइव क्लास में शामिल हों',
    uploadLecture: 'व्याख्यान अपलोड करें',
    lectureTitle: 'व्याख्यान शीर्षक',
    subject: 'विषय',
    description: 'विवरण',
    optimizeForLowBandwidth: 'कम बैंडविड्थ के लिए अनुकूलित करें',
    recordedLectures: 'रिकॉर्ड किए गए व्याख्यान',
    aiAssistant: 'AI सहायक',
    typeYourDoubt: 'अपना संदेह टाइप करें...',
    explainTopic: 'विषय समझाएं',
    summarizeLecture: 'व्याख्यान सारांश',
    answerQuiz: 'प्रश्न का उत्तर',
    howToUse: 'उपयोग कैसे करें',
    callSupport: 'कॉल सपोर्ट',
    tollFreeNumber: 'टोल-फ्री: 1800-XXX-XXXX',
    offlineMode: 'ऑफलाइन मोड',
    downloadForOffline: 'ऑफलाइन के लिए डाउनलोड',
    culturalGreeting: 'नमस्ते! सीखने में आपका स्वागत है',
    welcomeMessage: 'एडुइंडिया में आपका स्वागत है',
    todaysLectures: 'आज के व्याख्यान',
    myProgress: 'मेरी प्रगति',
    quickActions: 'त्वरित कार्य',
    recentActivity: 'हाल की गतिविधि',
    upcomingClasses: 'आगामी कक्षाएं',
    featuredCourses: 'विशेष पाठ्यक्रम',
    studyMaterials: 'अध्ययन सामग्री',
    practiceTests: 'अभ्यास परीक्षा',
    achievements: 'उपलब्धियां',
    notifications: 'सूचनाएं',
  },
  ta: {
    appName: 'எடுஇந்தியா',
    tagline: 'கிராமப்புற இந்தியாவிற்கான கல்வி',
    home: 'முகப்பு',
    lectures: 'விரிவுரைகள்',
    assignments: 'பணிகள்',
    discussions: 'விவாதங்கள்',
    profile: 'சுயவிவரம்',
    joinLiveClass: 'நேரடி வகுப்பில் சேரவும்',
    uploadLecture: 'விரிவுரையை பதிவேற்றவும்',
    lectureTitle: 'விரிவுரை தலைப்பு',
    subject: 'பாடம்',
    description: 'விளக்கம்',
    optimizeForLowBandwidth: 'குறைந்த அலைவரிசைக்கு மேம்படுத்தவும்',
    recordedLectures: 'பதிவு செய்யப்பட்ட விரிவுரைகள்',
    aiAssistant: 'AI உதவியாளர்',
    typeYourDoubt: 'உங்கள் சந்தேகத்தை தட்டச்சு செய்யவும்...',
    explainTopic: 'தலைப்பை விளக்கவும்',
    summarizeLecture: 'விரிவுரை சுருக்கம்',
    answerQuiz: 'வினாடி வினாவிற்கு பதில்',
    howToUse: 'எப்படி பயன்படுத்துவது',
    callSupport: 'அழைப்பு ஆதரவு',
    tollFreeNumber: 'கட்டணமில்லா: 1800-XXX-XXXX',
    offlineMode: 'ஆஃப்லைன் பயன்முறை',
    downloadForOffline: 'ஆஃப்லைனுக்காக பதிவிறக்கவும்',
    culturalGreeting: 'வணக்கம்! கற்றலுக்கு உங்களை வரவேற்கிறோம்',
    welcomeMessage: 'எடுஇந்தியாவிற்கு வரவேற்கிறோம்',
    todaysLectures: 'இன்றைய விரிவுரைகள்',
    myProgress: 'எனது முன்னேற்றம்',
    quickActions: 'விரைவு செயல்கள்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    upcomingClasses: 'வரவிருக்கும் வகுப்புகள்',
    featuredCourses: 'சிறப்பு பாடநெறிகள்',
    studyMaterials: 'படிப்பு பொருட்கள்',
    practiceTests: 'பயிற்சி தேர்வுகள்',
    achievements: 'சாதனைகள்',
    notifications: 'அறிவிப்புகள்',
  },
  te: {
    appName: 'ఎడుఇండియా',
    tagline: 'గ్రామీణ భారతదేశం కోసం విద్య',
    home: 'హోమ్',
    lectures: 'ఉపన్యాసాలు',
    assignments: 'అసైన్‌మెంట్లు',
    discussions: 'చర్చలు',
    profile: 'ప్రొఫైల్',
    joinLiveClass: 'లైవ్ క్లాస్‌లో చేరండి',
    uploadLecture: 'ఉపన్యాసాన్ని అప్‌లోడ్ చేయండి',
    lectureTitle: 'ఉపన్యాస శీర్షిక',
    subject: 'విషయం',
    description: 'వివరణ',
    optimizeForLowBandwidth: 'తక్కువ బ్యాండ్‌విడ్త్ కోసం ఆప్టిమైజ్ చేయండి',
    recordedLectures: 'రికార్డ్ చేసిన ఉపన్యాసాలు',
    aiAssistant: 'AI సహాయకుడు',
    typeYourDoubt: 'మీ సందేహాన్ని టైప్ చేయండి...',
    explainTopic: 'అంశాన్ని వివరించండి',
    summarizeLecture: 'ఉపన్యాస సారాంశం',
    answerQuiz: 'క్విజ్‌కు సమాధానం',
    howToUse: 'ఎలా ఉపయోగించాలి',
    callSupport: 'కాల్ సపోర్ట్',
    tollFreeNumber: 'టోల్-ఫ్రీ: 1800-XXX-XXXX',
    offlineMode: 'ఆఫ్‌లైన్ మోడ్',
    downloadForOffline: 'ఆఫ్‌లైన్ కోసం డౌన్‌లోడ్',
    culturalGreeting: 'నమస్కారం! అభ్యాసానికి మిమ్మల్ని స్వాగతిస్తున్నాము',
    welcomeMessage: 'ఎడుఇండియాకు స్వాగతం',
    todaysLectures: 'నేటి ఉపన్యాసాలు',
    myProgress: 'నా పురోగతి',
    quickActions: 'త్వరిత చర్యలు',
    recentActivity: 'ఇటీవలి కార్యకలాపం',
    upcomingClasses: 'రాబోయే తరగతులు',
    featuredCourses: 'ప్రత్యేక కోర్సులు',
    studyMaterials: 'అధ్యయన సామగ్రి',
    practiceTests: 'అభ్యాస పరీక్షలు',
    achievements: 'విజయాలు',
    notifications: 'నోటిఫికేషన్లు',
  },
  bn: {
    appName: 'এডুইন্ডিয়া',
    tagline: 'গ্রামীণ ভারতের জন্য শিক্ষা',
    home: 'হোম',
    lectures: 'বক্তৃতা',
    assignments: 'অ্যাসাইনমেন্ট',
    discussions: 'আলোচনা',
    profile: 'প্রোফাইল',
    joinLiveClass: 'লাইভ ক্লাসে যোগ দিন',
    uploadLecture: 'বক্তৃতা আপলোড করুন',
    lectureTitle: 'বক্তৃতার শিরোনাম',
    subject: 'বিষয়',
    description: 'বর্ণনা',
    optimizeForLowBandwidth: 'কম ব্যান্ডউইথের জন্য অপ্টিমাইজ করুন',
    recordedLectures: 'রেকর্ড করা বক্তৃতা',
    aiAssistant: 'AI সহায়ক',
    typeYourDoubt: 'আপনার সন্দেহ টাইপ করুন...',
    explainTopic: 'বিষয় ব্যাখ্যা করুন',
    summarizeLecture: 'বক্তৃতার সারসংক্ষেপ',
    answerQuiz: 'কুইজের উত্তর',
    howToUse: 'কীভাবে ব্যবহার করবেন',
    callSupport: 'কল সাপোর্ট',
    tollFreeNumber: 'টোল-ফ্রি: 1800-XXX-XXXX',
    offlineMode: 'অফলাইন মোড',
    downloadForOffline: 'অফলাইনের জন্য ডাউনলোড',
    culturalGreeting: 'নমস্কার! শেখার জগতে আপনাকে স্বাগতম',
    welcomeMessage: 'এডুইন্ডিয়ায় স্বাগতম',
    todaysLectures: 'আজকের বক্তৃতা',
    myProgress: 'আমার অগ্রগতি',
    quickActions: 'দ্রুত কর্ম',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    upcomingClasses: 'আসন্ন ক্লাস',
    featuredCourses: 'বিশেষ কোর্স',
    studyMaterials: 'অধ্যয়ন উপকরণ',
    practiceTests: 'অনুশীলন পরীক্ষা',
    achievements: 'অর্জন',
    notifications: 'বিজ্ঞপ্তি',
  },
  mr: {
    appName: 'एडुइंडिया',
    tagline: 'ग्रामीण भारतासाठी शिक्षण',
    home: 'होम',
    lectures: 'व्याख्याने',
    assignments: 'असाइनमेंट',
    discussions: 'चर्चा',
    profile: 'प्रोफाइल',
    joinLiveClass: 'लाइव्ह क्लासमध्ये सामील व्हा',
    uploadLecture: 'व्याख्यान अपलोड करा',
    lectureTitle: 'व्याख्यान शीर्षक',
    subject: 'विषय',
    description: 'वर्णन',
    optimizeForLowBandwidth: 'कमी बँडविड्थसाठी ऑप्टिमाइझ करा',
    recordedLectures: 'रेकॉर्ड केलेली व्याख्याने',
    aiAssistant: 'AI सहाय्यक',
    typeYourDoubt: 'तुमची शंका टाइप करा...',
    explainTopic: 'विषय स्पष्ट करा',
    summarizeLecture: 'व्याख्यान सारांश',
    answerQuiz: 'प्रश्नमंजुषाचे उत्तर',
    howToUse: 'कसे वापरावे',
    callSupport: 'कॉल सपोर्ट',
    tollFreeNumber: 'टोल-फ्री: 1800-XXX-XXXX',
    offlineMode: 'ऑफलाइन मोड',
    downloadForOffline: 'ऑफलाइनसाठी डाउनलोड',
    culturalGreeting: 'नमस्कार! शिकण्यात तुमचे स्वागत आहे',
    welcomeMessage: 'एडुइंडियामध्ये स्वागत आहे',
    todaysLectures: 'आजची व्याख्याने',
    myProgress: 'माझी प्रगती',
    quickActions: 'त्वरित क्रिया',
    recentActivity: 'अलीकडील क्रियाकलाप',
    upcomingClasses: 'येणारे वर्ग',
    featuredCourses: 'वैशिष्ट्यीकृत अभ्यासक्रम',
    studyMaterials: 'अभ्यास साहित्य',
    practiceTests: 'सराव चाचण्या',
    achievements: 'यश',
    notifications: 'सूचना',
  },
  gu: {
    appName: 'એડુઇન્ડિયા',
    tagline: 'ગ્રામીણ ભારત માટે શિક્ષણ',
    home: 'હોમ',
    lectures: 'લેક્ચર',
    assignments: 'અસાઇનમેન્ટ',
    discussions: 'ચર્ચા',
    profile: 'પ્રોફાઇલ',
    joinLiveClass: 'લાઇવ ક્લાસમાં જોડાઓ',
    uploadLecture: 'લેક્ચર અપલોડ કરો',
    lectureTitle: 'લેક્ચર શીર્ષક',
    subject: 'વિષય',
    description: 'વર્ણન',
    optimizeForLowBandwidth: 'ઓછી બેન્ડવિડ્થ માટે ઓપ્ટિમાઇઝ કરો',
    recordedLectures: 'રેકોર્ડ કરેલા લેક્ચર',
    aiAssistant: 'AI સહાયક',
    typeYourDoubt: 'તમારી શંકા ટાઇપ કરો...',
    explainTopic: 'વિષય સમજાવો',
    summarizeLecture: 'લેક્ચર સારાંશ',
    answerQuiz: 'ક્વિઝનો જવાબ',
    howToUse: 'કેવી રીતે ઉપયોગ કરવો',
    callSupport: 'કોલ સપોર્ટ',
    tollFreeNumber: 'ટોલ-ફ્રી: 1800-XXX-XXXX',
    offlineMode: 'ઓફલાઇન મોડ',
    downloadForOffline: 'ઓફલાઇન માટે ડાઉનલોડ',
    culturalGreeting: 'નમસ્તે! શીખવામાં તમારું સ્વાગત છે',
    welcomeMessage: 'એડુઇન્ડિયામાં સ્વાગત છે',
    todaysLectures: 'આજના લેક્ચર',
    myProgress: 'મારી પ્રગતિ',
    quickActions: 'ઝડપી ક્રિયાઓ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    upcomingClasses: 'આવનારા વર્ગો',
    featuredCourses: 'વિશેષ કોર્સ',
    studyMaterials: 'અભ્યાસ સામગ્રી',
    practiceTests: 'પ્રેક્ટિસ ટેસ્ટ',
    achievements: 'સિદ્ધિઓ',
    notifications: 'સૂચનાઓ',
  },
  kn: {
    appName: 'ಎಡುಇಂಡಿಯಾ',
    tagline: 'ಗ್ರಾಮೀಣ ಭಾರತಕ್ಕಾಗಿ ಶಿಕ್ಷಣ',
    home: 'ಮುಖ್ಯಪುಟ',
    lectures: 'ಉಪನ್ಯಾಸಗಳು',
    assignments: 'ಕಾರ್ಯಗಳು',
    discussions: 'ಚರ್ಚೆಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    joinLiveClass: 'ಲೈವ್ ಕ್ಲಾಸ್‌ಗೆ ಸೇರಿ',
    uploadLecture: 'ಉಪನ್ಯಾಸವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    lectureTitle: 'ಉಪನ್ಯಾಸ ಶೀರ್ಷಿಕೆ',
    subject: 'ವಿಷಯ',
    description: 'ವಿವರಣೆ',
    optimizeForLowBandwidth: 'ಕಡಿಮೆ ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್‌ಗಾಗಿ ಆಪ್ಟಿಮೈಜ್ ಮಾಡಿ',
    recordedLectures: 'ರೆಕಾರ್ಡ್ ಮಾಡಿದ ಉಪನ್ಯಾಸಗಳು',
    aiAssistant: 'AI ಸಹಾಯಕ',
    typeYourDoubt: 'ನಿಮ್ಮ ಸಂದೇಹವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    explainTopic: 'ವಿಷಯವನ್ನು ವಿವರಿಸಿ',
    summarizeLecture: 'ಉಪನ್ಯಾಸ ಸಾರಾಂಶ',
    answerQuiz: 'ಕ್ವಿಜ್‌ಗೆ ಉತ್ತರ',
    howToUse: 'ಹೇಗೆ ಬಳಸುವುದು',
    callSupport: 'ಕಾಲ್ ಸಪೋರ್ಟ್',
    tollFreeNumber: 'ಟೋಲ್-ಫ್ರೀ: 1800-XXX-XXXX',
    offlineMode: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
    downloadForOffline: 'ಆಫ್‌ಲೈನ್‌ಗಾಗಿ ಡೌನ್‌ಲೋಡ್',
    culturalGreeting: 'ನಮಸ್ಕಾರ! ಕಲಿಕೆಗೆ ನಿಮಗೆ ಸ್ವಾಗತ',
    welcomeMessage: 'ಎಡುಇಂಡಿಯಾಗೆ ಸ್ವಾಗತ',
    todaysLectures: 'ಇಂದಿನ ಉಪನ್ಯಾಸಗಳು',
    myProgress: 'ನನ್ನ ಪ್ರಗತಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    upcomingClasses: 'ಮುಂಬರುವ ತರಗತಿಗಳು',
    featuredCourses: 'ವಿಶೇಷ ಕೋರ್ಸ್‌ಗಳು',
    studyMaterials: 'ಅಧ್ಯಯನ ಸಾಮಗ್ರಿಗಳು',
    practiceTests: 'ಅಭ್ಯಾಸ ಪರೀಕ್ಷೆಗಳು',
    achievements: 'ಸಾಧನೆಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
  },
  ml: {
    appName: 'എഡുഇന്ത്യ',
    tagline: 'ഗ്രാമീണ ഇന്ത്യയ്ക്കുള്ള വിദ്യാഭ്യാസം',
    home: 'ഹോം',
    lectures: 'പ്രഭാഷണങ്ങൾ',
    assignments: 'അസൈൻമെന്റുകൾ',
    discussions: 'ചർച്ചകൾ',
    profile: 'പ്രൊഫൈൽ',
    joinLiveClass: 'ലൈവ് ക്ലാസിൽ ചേരുക',
    uploadLecture: 'പ്രഭാഷണം അപ്‌ലോഡ് ചെയ്യുക',
    lectureTitle: 'പ്രഭാഷണ ശീർഷകം',
    subject: 'വിഷയം',
    description: 'വിവരണം',
    optimizeForLowBandwidth: 'കുറഞ്ഞ ബാൻഡ്‌വിഡ്ത്തിനായി ഒപ്റ്റിമൈസ് ചെയ്യുക',
    recordedLectures: 'റെക്കോർഡ് ചെയ്ത പ്രഭാഷണങ്ങൾ',
    aiAssistant: 'AI സഹായി',
    typeYourDoubt: 'നിങ്ങളുടെ സംശയം ടൈപ്പ് ചെയ്യുക...',
    explainTopic: 'വിഷയം വിശദീകരിക്കുക',
    summarizeLecture: 'പ്രഭാഷണ സംഗ്രഹം',
    answerQuiz: 'ക്വിസിന് ഉത്തരം',
    howToUse: 'എങ്ങനെ ഉപയോഗിക്കാം',
    callSupport: 'കോൾ സപ്പോർട്ട്',
    tollFreeNumber: 'ടോൾ-ഫ്രീ: 1800-XXX-XXXX',
    offlineMode: 'ഓഫ്‌ലൈൻ മോഡ്',
    downloadForOffline: 'ഓഫ്‌ലൈനിനായി ഡൗൺലോഡ്',
    culturalGreeting: 'നമസ്കാരം! പഠനത്തിലേക്ക് സ്വാഗതം',
    welcomeMessage: 'എഡുഇന്ത്യയിലേക്ക് സ്വാഗതം',
    todaysLectures: 'ഇന്നത്തെ പ്രഭാഷണങ്ങൾ',
    myProgress: 'എന്റെ പുരോഗതി',
    quickActions: 'പെട്ടെന്നുള്ള പ്രവർത്തനങ്ങൾ',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    upcomingClasses: 'വരാനിരിക്കുന്ന ക്ലാസുകൾ',
    featuredCourses: 'പ്രത്യേക കോഴ്‌സുകൾ',
    studyMaterials: 'പഠന സാമഗ്രികൾ',
    practiceTests: 'പരിശീലന പരീക്ഷകൾ',
    achievements: 'നേട്ടങ്ങൾ',
    notifications: 'അറിയിപ്പുകൾ',
  },
  pa: {
    appName: 'ਐਡੂਇੰਡੀਆ',
    tagline: 'ਪੇਂਡੂ ਭਾਰਤ ਲਈ ਸਿੱਖਿਆ',
    home: 'ਘਰ',
    lectures: 'ਲੈਕਚਰ',
    assignments: 'ਅਸਾਈਨਮੈਂਟ',
    discussions: 'ਚਰਚਾ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    joinLiveClass: 'ਲਾਈਵ ਕਲਾਸ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    uploadLecture: 'ਲੈਕਚਰ ਅਪਲੋਡ ਕਰੋ',
    lectureTitle: 'ਲੈਕਚਰ ਸਿਰਲੇਖ',
    subject: 'ਵਿਸ਼ਾ',
    description: 'ਵਰਣਨ',
    optimizeForLowBandwidth: 'ਘੱਟ ਬੈਂਡਵਿਡਥ ਲਈ ਅਨੁਕੂਲਿਤ ਕਰੋ',
    recordedLectures: 'ਰਿਕਾਰਡ ਕੀਤੇ ਲੈਕਚਰ',
    aiAssistant: 'AI ਸਹਾਇਕ',
    typeYourDoubt: 'ਆਪਣਾ ਸ਼ੱਕ ਟਾਈਪ ਕਰੋ...',
    explainTopic: 'ਵਿਸ਼ੇ ਦੀ ਵਿਆਖਿਆ ਕਰੋ',
    summarizeLecture: 'ਲੈਕਚਰ ਸਾਰ',
    answerQuiz: 'ਕੁਇਜ਼ ਦਾ ਜਵਾਬ',
    howToUse: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ',
    callSupport: 'ਕਾਲ ਸਪੋਰਟ',
    tollFreeNumber: 'ਟੋਲ-ਫ੍ਰੀ: 1800-XXX-XXXX',
    offlineMode: 'ਔਫਲਾਈਨ ਮੋਡ',
    downloadForOffline: 'ਔਫਲਾਈਨ ਲਈ ਡਾਊਨਲੋਡ',
    culturalGreeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਸਿੱਖਣ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    welcomeMessage: 'ਐਡੂਇੰਡੀਆ ਵਿੱਚ ਸੁਆਗਤ ਹੈ',
    todaysLectures: 'ਅੱਜ ਦੇ ਲੈਕਚਰ',
    myProgress: 'ਮੇਰੀ ਤਰੱਕੀ',
    quickActions: 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
    recentActivity: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    upcomingClasses: 'ਆਉਣ ਵਾਲੀਆਂ ਕਲਾਸਾਂ',
    featuredCourses: 'ਵਿਸ਼ੇਸ਼ ਕੋਰਸ',
    studyMaterials: 'ਅਧਿਐਨ ਸਮੱਗਰੀ',
    practiceTests: 'ਅਭਿਆਸ ਟੈਸਟ',
    achievements: 'ਪ੍ਰਾਪਤੀਆਂ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
  },
  or: {
    appName: 'ଏଡୁଇଣ୍ଡିଆ',
    tagline: 'ଗ୍ରାମୀଣ ଭାରତ ପାଇଁ ଶିକ୍ଷା',
    home: 'ହୋମ',
    lectures: 'ବକ୍ତୃତା',
    assignments: 'ଆସାଇନମେଣ୍ଟ',
    discussions: 'ଆଲୋଚନା',
    profile: 'ପ୍ରୋଫାଇଲ',
    joinLiveClass: 'ଲାଇଭ କ୍ଲାସରେ ଯୋଗ ଦିଅନ୍ତୁ',
    uploadLecture: 'ବକ୍ତୃତା ଅପଲୋଡ କରନ୍ତୁ',
    lectureTitle: 'ବକ୍ତୃତା ଶୀର୍ଷକ',
    subject: 'ବିଷୟ',
    description: 'ବର୍ଣ୍ଣନା',
    optimizeForLowBandwidth: 'କମ ବ୍ୟାଣ୍ଡୱିଡଥ ପାଇଁ ଅପ୍ଟିମାଇଜ କରନ୍ତୁ',
    recordedLectures: 'ରେକର୍ଡ ହୋଇଥିବା ବକ୍ତୃତା',
    aiAssistant: 'AI ସହାୟକ',
    typeYourDoubt: 'ଆପଣଙ୍କ ସନ୍ଦେହ ଟାଇପ କରନ୍ତୁ...',
    explainTopic: 'ବିଷୟ ବ୍ୟାଖ୍ୟା କରନ୍ତୁ',
    summarizeLecture: 'ବକ୍ତୃତା ସାରାଂଶ',
    answerQuiz: 'କୁଇଜର ଉତ୍ତର',
    howToUse: 'କିପରି ବ୍ୟବହାର କରିବେ',
    callSupport: 'କଲ ସପୋର୍ଟ',
    tollFreeNumber: 'ଟୋଲ-ଫ୍ରି: 1800-XXX-XXXX',
    offlineMode: 'ଅଫଲାଇନ ମୋଡ',
    downloadForOffline: 'ଅଫଲାଇନ ପାଇଁ ଡାଉନଲୋଡ',
    culturalGreeting: 'ନମସ୍କାର! ଶିକ୍ଷାରେ ଆପଣଙ୍କୁ ସ୍ୱାଗତ',
    welcomeMessage: 'ଏଡୁଇଣ୍ଡିଆରେ ସ୍ୱାଗତ',
    todaysLectures: 'ଆଜିର ବକ୍ତୃତା',
    myProgress: 'ମୋର ଅଗ୍ରଗତି',
    quickActions: 'ଦ୍ରୁତ କାର୍ଯ୍ୟ',
    recentActivity: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    upcomingClasses: 'ଆଗାମୀ କ୍ଲାସ',
    featuredCourses: 'ବିଶେଷ କୋର୍ସ',
    studyMaterials: 'ଅଧ୍ୟୟନ ସାମଗ୍ରୀ',
    practiceTests: 'ଅଭ୍ୟାସ ପରୀକ୍ଷା',
    achievements: 'ସଫଳତା',
    notifications: 'ବିଜ୍ଞପ୍ତି',
  },
  as: {
    appName: 'এডুইণ্ডিয়া',
    tagline: 'গ্ৰাম্য ভাৰতৰ বাবে শিক্ষা',
    home: 'হোম',
    lectures: 'বক্তৃতা',
    assignments: 'এছাইনমেণ্ট',
    discussions: 'আলোচনা',
    profile: 'প্ৰফাইল',
    joinLiveClass: 'লাইভ ক্লাছত যোগদান কৰক',
    uploadLecture: 'বক্তৃতা আপলোড কৰক',
    lectureTitle: 'বক্তৃতাৰ শিৰোনাম',
    subject: 'বিষয়',
    description: 'বৰ্ণনা',
    optimizeForLowBandwidth: 'কম বেণ্ডৱিডথৰ বাবে অপ্টিমাইজ কৰক',
    recordedLectures: 'ৰেকৰ্ড কৰা বক্তৃতা',
    aiAssistant: 'AI সহায়ক',
    typeYourDoubt: 'আপোনাৰ সন্দেহ টাইপ কৰক...',
    explainTopic: 'বিষয় ব্যাখ্যা কৰক',
    summarizeLecture: 'বক্তৃতাৰ সাৰাংশ',
    answerQuiz: 'কুইজৰ উত্তৰ',
    howToUse: 'কেনেকৈ ব্যৱহাৰ কৰিব',
    callSupport: 'কল সাপোৰ্ট',
    tollFreeNumber: 'টোল-ফ্ৰী: 1800-XXX-XXXX',
    offlineMode: 'অফলাইন মোড',
    downloadForOffline: 'অফলাইনৰ বাবে ডাউনলোড',
    culturalGreeting: 'নমস্কাৰ! শিক্ষাত আপোনাক স্বাগতম',
    welcomeMessage: 'এডুইণ্ডিয়াত স্বাগতম',
    todaysLectures: 'আজিৰ বক্তৃতা',
    myProgress: 'মোৰ অগ্ৰগতি',
    quickActions: 'দ্ৰুত কাৰ্য',
    recentActivity: 'শেহতীয়া কাৰ্যকলাপ',
    upcomingClasses: 'আহিব লগা ক্লাছ',
    featuredCourses: 'বিশেষ পাঠ্যক্ৰম',
    studyMaterials: 'অধ্যয়ন সামগ্ৰী',
    practiceTests: 'অনুশীলন পৰীক্ষা',
    achievements: 'সাফল্য',
    notifications: 'জাননী',
  },
  raj: {
    appName: 'एडुइंडिया',
    tagline: 'राजस्थानी गांवां री शिक्षा',
    home: 'घर',
    lectures: 'पाठ',
    assignments: 'काम',
    discussions: 'बात-चीत',
    profile: 'प्रोफाइल',
    joinLiveClass: 'लाइव क्लास में आवो',
    uploadLecture: 'पाठ अपलोड करो',
    lectureTitle: 'पाठ नाम',
    subject: 'विषय',
    description: 'ब्यौरो',
    optimizeForLowBandwidth: 'कम इंटरनेट के लिए ठीक करो',
    recordedLectures: 'रिकॉर्ड किए गए पाठ',
    aiAssistant: 'AI सहायक',
    typeYourDoubt: 'आपनो संदेह लिखो...',
    explainTopic: 'विषय समझावो',
    summarizeLecture: 'पाठ सारांश',
    answerQuiz: 'सवाल रो जवाब',
    howToUse: 'कैसे इस्तेमाल करें',
    callSupport: 'कॉल सपोर्ट',
    tollFreeNumber: 'टोल-फ्री: 1800-XXX-XXXX',
    offlineMode: 'ऑफलाइन मोड',
    downloadForOffline: 'ऑफलाइन के लिए डाउनलोड',
    culturalGreeting: 'खम्मा घणी! सीखने में आपका स्वागत',
    welcomeMessage: 'एडुइंडिया में खम्मा घणी',
    todaysLectures: 'आज के पाठ',
    myProgress: 'म्हारी प्रगति',
    quickActions: 'झटपट काम',
    recentActivity: 'हाल री गतिविधि',
    upcomingClasses: 'आने वाली क्लास',
    featuredCourses: 'खास कोर्स',
    studyMaterials: 'पढ़ाई री सामग्री',
    practiceTests: 'अभ्यास परीक्षा',
    achievements: 'सफलता',
    notifications: 'सूचना',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('raj'); // Default to Rajasthani

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};